name: CI

on: push

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Init
        run: make init
      
      - name: build
        run: make build
       
      - name: up
        run: make up
          
      - name: Pytest
        run: pytest
